### ISSUE TITLE
Gamecube Chao Garden save error

### ISSUE THREAD

**Issue by Arlisbloxer05** [dfrood/SA2SaveUtility#3] opened 2019-06-01 02:06 UTC
![image](https://user-images.githubusercontent.com/45444483/58742150-00c7e200-83f0-11e9-9628-db50b4120b0e.png)

hi, im having an issue with loading my SA2B chao garden save data from the gamecube, is there any possible fix for this?

**Comment by dfrood** [comment] 2019-06-02 20:47
Hello, it appears a value your chao has is outside the values I have assigned. Could you send your save to me so I can take a look at it? Thanks!

**Comment by Arlisbloxer05** [comment] 2019-06-02 21:17
Here ya go

**Comment by Arlisbloxer05** [comment] 2019-06-02 21:18
[8P-GSNE-SONIC2B__5f____5f__ALF.zip](https://github.com/dfrood/SA2SaveUtility/files/3245233/8P-GSNE-SONIC2B__5f____5f__ALF.zip)
Here ya go (had to redo this)

**Comment by dfrood** [comment] 2019-06-02 22:52
Hi, thanks for providing your save. If you use the version I just released you should be able to load your save just fine.

The issue is that I don't have the chao egg colours that are textures implemented so it will currently just display as "<Placeholder>" for your Ruby chao Nesa until I've properly implemented all the possible egg colour names.

**Comment by Arlisbloxer05** [comment] 2019-06-02 23:07
cheers mate! and thanks for the heads up about the egg colors so I dont screw something up!

**Comment by dfrood** [comment] 2019-06-05 14:42
Release 0.4.1.0 now includes the Texture Egg Colours (for Gamecube), closing the issue now.

**Closed by dfrood** 2019-06-05 14:42 UTC
Labels: bug
